config/routes.rb
Rails.application.routes.draw do
    


    root 'pages#home'
    
  get '/home', to: 'pages#home'
  
    resources :reecipes do
      member do 
        post 'like'
      end 
    end 
      
      resources :chefs, except: [:new]
     
      get '/register', to: 'chefs#new'  
     
    get '/login', to: "logins#new"
    post '/login', to: "logins#create"
    get '/logout', to: "logins#destroy"
    
  end

app/models/chef.rb
class Chef < ActiveRecord::Base
 has_many :reecipes
  has_many :likes
  
    before_save {self.email = email.downcase}
  validates :chefname, presence: true, length:{ minimum: 3, maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length:{  maximum: 35}, 
                                      uniqueness: {case_sensitive: false},
                                      format: {with: VALID_EMAIL_REGEX}
                                      
    has_secure_password                                  
end

app/models/like.rb
class Like < ActiveRecord::Base
   belongs_to :chef
   belongs_to :reecipe
   
   validates_uniqueness_of :chef, scope: :reecipe
end

app/models/reecipe.rb
class Reecipe < ActiveRecord::Base
    belongs_to :chef
    has_many :likes
    
    validates :chef_id, presence: true
    validates :name, presence: true, length:{ minimum: 5, maximum: 20}
    validates :summary, presence: true, length:{ minimum: 10, maximum: 100}
    validates :description, presence: true, length:{ minimum: 20, maximum: 200}
    mount_uploader :picture, PictureUploader
    validate :picture_size
    default_scope -> {order(updated_at: :desc)}
    
    def thumbs_up_total
        self.likes.where(like: true).size
    end
    
    def thumbs_down_total
    self.likes.where(like: false).size        
    end
    
    
    private
     def picture_size
         if picture.size >5.megabytes
             errors.add(:picture, "should be less than 5MB")
         end
     end
     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  
  
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

   def logged_in?
      !!current_user
   end
     
     
      def require_user
        if !logged_in?
         flash[:danger] = "you must to logged in to do so "
         redirect_to :back
        end
      end 
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
   before_action :set_chef, only: [:edit, :update, :show]
   before_action :require_same_user, only: [:edit, :update]
   
  def index 
        @chefs = Chef.paginate(page: params[:page], per_page: 3)
  end
  
  
  def new
    @chef = Chef.new
  end 
  
  def create 
       @chef = Chef.new(chef_params)
       if @chef.save
          flash[:success] = "your account has been created successfully"
          session[:chef_id] = @chef.id
         redirect_to reecipes_path
       else
           render 'new'
       end 
  end     
  
  def edit

  end 
  
  def update
      
    if @chef.update(chef_params)
      flash[:success] = "your profile has been updated successfully"
       redirect_to chef_path(@chef) #to  show chef page
    else
       render 'edit'
    end
  end 
  
  def show
       
          @reecipes = @chef.reecipes.paginate(page: params[:page] , per_page: 1)
  end 
  
  private
 
        def chef_params
             params.require(:chef).permit(:chefname, :email, :password)
        end 
        
         def set_chef
           @chef = Chef.find(params[:id])
         end
         
        def require_same_user
           if current_user != @chef
            flash[:danger] = "you cant edit others profile"
            redirect_to root_path
           end 
        end
end 

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    
    def new
        
    end
    
    def create
       chef = Chef.find_by(email: params[:email])
        if chef && chef.authenticate(params[:password])
            session[:chef_id] = chef.id
            
         flash[:success] = "you are logged in"
          redirect_to reecipes_path
           
        else
           flash.now[:danger] = "your email or password doesnt match"
           render 'new'
        end 
       
    end
    
    def destroy
        
        session[:chef_id] = nil
        flash[:success] = "successfully logged out"
        redirect_to root_path
        
    end
    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
        redirect_to reecipes_path if logged_in?
    end
    
end

app/controllers/reecipes_controller.rb
class ReecipesController < ApplicationController
   before_action :set_reecipe, only: [:edit, :update, :show, :like]
   before_action :require_user, except: [:show, :index]
   before_action :require_same_user, only: [:edit, :update]
   
  def index
    @reecipes = Reecipe.paginate(page: params[:page], per_page: 4 )
  end
  
  def show
   
  end 
  
  def new
    @reecipe = Reecipe.new
  end 
  
  def create 
         @reecipe = Reecipe.new(reecipe_params)
         @reecipe.chef = current_user
         
         
   if @reecipe.save
     flash[:success] = "your reecipe was created successfully!"
     redirect_to reecipes_path
   else
     render :new
   end 
  end

    def edit
      
    end
    
    def update
      
      if @reecipe.update(reecipe_params)
        flash[:success] = "your reecipe was updated successfully"
        redirect_to reecipe_path(@reecipe)
      else 
        render :edit
      end 
    end 

      def like
      
       Like.create(like: params[:like], chef: current_user, reecipe: @reecipe)
       if like.valid?
         flash[:success] = "your selection was success"
       redirect_to :back
     else
       flash[:danger] = "you can only like/dislike a reecipe once"
       end 
      end 
   
      
    private
    
            def reecipe_params
            params.require(:reecipe).permit(:name, :summary, :description, :picture)
            end
            
          def set_reecipe
           @reecipe = Reecipe.find(params[:id])
          end
         
        def require_same_user
           if current_user != @reecipe.chef
            flash[:danger] = "you can't edit others profile"
            redirect_to reecipes_path
           end 
        end
end

 

app/helpers/application_helper.rb
module ApplicationHelper
    
   def gravatar_for(chef, options = { size: 90 })
        gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
    end
    
end

app/helpers/reecipes_helper.rb
module ReecipesHelper
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class ="row">
    <div class ="well-col-md-8 col-md-offset-2">
        <%= form_for @chef do |f| %>
        <%= f.label :chefname %>
        <%= f.text_field :chefname %>
        
        <%= f.label :email %>
        <%= f.email_field :email %>
        
        <%= f.label :password %>
        <%= f.password_field :password %>
        
        
    
        <%= f.submit( @chef.new_record? ? 'Register':'Edit Profile',class: "btn-btn-success") %>
        <% end %>
    </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title',title: "Edit you profile"%>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>


<ul class="nav nav-tabs">
  <li>
        <%= link_to "Reecipes", reecipes_path %>
    </li>
   
      <li class='active'>
        <%= link_to "Chefs",chefs_path %>
    </li>
</ul>


<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= will_paginate %>
    </div>
</div>

<% @chefs.each do |chef| %>
   <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
     <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
     <p>
         <h5>Chef name: <%= chef.chefname %>
         </h5>
     </p>
    </div>
</div>
    
<% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title',title: "Register your account"%>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title',title: "Chef: " + @chef.chefname %>


<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 200 %>
<hr/>
 </div>
</div>

<div class="row">
    <div class="col-md-4 col-md-offset-4-center">
        <h3><em>Reecipes:</em></h3>
        <%= will_paginate @reecipes %>
    </div>
</div>

    <% @reecipes.each do |reecipe| %>
    <div class="row">
    <div class="col-lg-5 well col-lg-offset-3">
  <h4><%= link_to reecipe.name, reecipe_path(reecipe)%></h4>
  <p><%= reecipe.summary %></p>
  <p>
      <span class='quiet'><small>created: <%= time_ago_in_words(reecipe.created_at) %>ago,</small></span>
      <span class='quiet'><small>updated: <%= time_ago_in_words(reecipe.updated_at) %>ago</small></span>
      </p>
          <div class="pull-right">
                <%= link_to like_reecipe_path(reecipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= reecipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_reecipe_path(reecipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= reecipe.thumbs_down_total %>
                <% end %>&nbsp&nbsp&nbsp&nbsp
                
            </div>
            
</div>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy:myrecipes sumit 2015</p>
</div>

app/views/layouts/_message.html.erb
<div class= "row">
    <div class= "col-md-16">
    <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %>
    <a class="close" data-dismiss="alert">&#215;</a>
        
    </div>
    <% end %>
    </div>  
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "myRecipes", root_path, class: "btn btn-lg btn-success", id: "logo" %>
  
    <div class="nav_item">
      <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
    </div>
    
    <div class="nav_item">
      <%= link_to "link1", "", class: "btn btn-default btn-warning" %>
    </div>
    
    <% if logged_in? %>
    <div class="nav_item"> 
      <%= link_to "New Reecipe", new_reecipe_path, class: "btn btn-default btn-warning" %>
    </div>
    <ul class="nav_item">
      <li class="dropdown">
        <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
        <%= current_user.chefname %> <b class="caret"></b>
        <% end %>
        <ul class='dropdown-menu'>
          <li><%= link_to "view profile", chef_path(current_user) %></li>
          <li><%= link_to "Edit profile", edit_chef_path(current_user) %></li>
          <li class= "divider"></li>
          <li><%= link_to "logout", logout_path%></li>
          
        </ul>
        
      </li>
    </ul>
    <% else %>
    <div class= "nav_item">
      <%= link_to "Login", login_path, class: "btn btn-default btn-success" %>
      
    </div>
    <% end %>
    
  </div>
</header>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>recipe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation'%>
<div class="container">
<%= render 'layouts/message' %>
<%= yield %>
<%= render 'layouts/footer'%>
</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Login in' %>


<div class= "row">
    <div class= "well col-md-6 col-md-offset-3">
         <%= form_tag '/login' do %>
         
            <%= label_tag :email %>
            <%= text_field_tag :email %>
            
            <%= label_tag :password %>
            <%= password_field_tag :password %>
            
            <%= submit_tag 'Login', class: "btn-btn-success" %>

<% end %>
</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
<h1>welcome to myRecipes App</h1>
<h2>this is myrecipe portal contains all kind of dishes to help you for preparation</h2>

<%= link_to"sign up now!",register_path, class: "btn btn-lg btn-success"%>
</div>
<div class= "row">
    <div class="col-lg-4">
        <h2 class ="midrow">
            view Recipes as guest user
            </h2>
            <h3 class= "left">browse and view recipes as a guest and sign later</h3>
        <p><%= link_to "browse recipe listing",reecipes_path,class: "btn btn-warning btn-small"%></p> 
                </div>
        
    <div class="col-lg-4">
        <h2 class ="midrow">
            Sign in to your account
            </h2>
            <h3 class= "left">Sign in to Add/Update your recipes</h3>
        <p><%= link_to "Login to your account", new_reecipe_path, class: "btn btn-warning btn-small"%></p> 
                </div>
        <div class="col-lg-4">
        <h2 class ="midrow">
            view Recipes as guest user
            </h2>
            <h3 class= "left">browse and view recipes as a guest and sign later</h3>
        <p><%= link_to "browse recipe listing","",class: "btn btn-warning btn-small"%></p> 
        </div>
        
    

app/views/reecipes/_form.html.erb
<%= render 'shared/errors', obj: @reecipe %>

<div class ="row">
    <div class ="well-col-md-8 col-md-offset-2">
        <%= form_for(@reecipe, html: { multipart: true }) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        
        <%= f.label :summary %>
        <%= f.text_field :summary %>
        
        <%= f.label :description %>
        <%= f.text_area :description, rows:10%>
        
        
    <span class="picture">
        <%= f.file_field :picture, accept: 'image/jgeg,image/gif,image/png' %>
    </span>
        
        <%= f.submit( @reecipe.new_record? ? 'Create Reecipe':'Edit Reecipe',class: "btn-btn-success") %>
        <% end %>
    </div>
</div>

<script type="text\javascript">
    $('#reecipe_picture').bind('change', function() {
        size_in_megabytes = this.file[0].size/1024/1024;
        if(size_in_megabytes > 5){
            alert('maximum file size is 5MB, please choose a smaller file.');
        }
    });
</script>

app/views/reecipes/edit.html.erb
<%= render 'shared/page_title',title: "Edit Reecipes"%>

<%= render 'form' %>

app/views/reecipes/index.html.erb
<%= render 'shared/page_title',title: "All Reecipes"%>

<ul class="nav nav-tabs">
    <li class='active'>
        <%= link_to "Reecipes", reecipes_path %>
    </li>
   
  <li>
        <%= link_to "Chefs",chefs_path %>
    </li>
</ul>

<%= will_paginate %>


<% @reecipes.each do |reecipe| %>
<div class="row">
    <div class="col-md-2">
        <section class="chef_info center">
             <%= link_to gravatar_for(reecipe.chef, size: 100), chef_path(reecipe.chef) %>
            <h5>Chef name: <%= reecipe.chef.chefname %></h5>
           
            
</section>
</div>
<div class="col-lg-5 well">
  <h4><%= link_to reecipe.name, reecipe_path(reecipe)%></h4>
  <p><%= reecipe.summary %></p>
  <p>
      <span class='quiet'><small>created: <%= time_ago_in_words(reecipe.created_at) %>ago,</small></span>
      <span class='quiet'><small>updated: <%= time_ago_in_words(reecipe.updated_at) %>ago</small></span>
      </p>
      <div class="pull-right">
                <%= link_to like_reecipe_path(reecipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= reecipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_reecipe_path(reecipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= reecipe.thumbs_down_total %>
                <% end %>&nbsp&nbsp&nbsp&nbsp
                
            </div>
            
</div>
<div class="col-md-4">
    <%= image_tag(reecipe.picture.url, size: "140X150", class: "gravatar") if reecipe.picture? %>
</div>
<hr/>
</div>
<% end %> 
<%= will_paginate %>

app/views/reecipes/new.html.erb
<%= render 'shared/page_title',title: "Create New Reecipes"%>

<%= render 'form' %>

app/views/reecipes/show.html.erb
<%= render 'shared/page_title',title: @reecipe.name %>
<div class="row">
    <div class="col-md-4-pull-right center">
    <%= link_to gravatar_for(@reecipe.chef, size: 200), chef_path(@reecipe.chef) %>
    <p>
    <h5>Brought to u by: <%= @reecipe.chef.chefname %></h5>
    </p>
    </div>
    <div class= "col-md-8">
        <% if logged_in? and @reecipe.chef == current_user %>
        
        <%= link_to "Edit this reecipe", edit_reecipe_path(@reecipe), class: "btn btn-success pull-right" %>
        <% end %>
        <h3><%= @reecipe.summary %></h3>
        <div class="show_reecipe">
            <%= image_tag(@reecipe.picture.url, class: "gravatar") if @reecipe.picture? %>
        </div>
        <div class= "well">
            <p>
                <strong>
                    Steps:
                </strong>
            </p>
            <%= simple_format(@reecipe.description) %>
            <div class="pull-right">
                <%= link_to like_reecipe_path(@reecipe, like: true), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp <%= @reecipe.thumbs_up_total %>
                <% end %> &nbsp&nbsp&nbsp&nbsp
                <%= link_to like_reecipe_path(@reecipe, like: false), method: :post do %>
                <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp <%= @reecipe.thumbs_down_total %>
                <% end %>&nbsp&nbsp&nbsp&nbsp
                
            </div>
            
                
        </div>  
    </div>
</div>
    <h5><%= link_to "Return Reecipe listing", reecipes_path, class: "btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
        <h5>please correct the following errors:</h5>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
    <h1><%= title %></h1>
    <hr/>
</p>